import Head from "next/head";
import Hero from "../components/Hero";

export default function Weebapp() {
  return (
    <div>
      <Head>
        <title>Weebapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weeblogo40.png" />
      </Head>
      <Hero />
    </div>
  );
}
