import Head from "next/head";
import Navbar from "../components/Navbar";
import Illust from "../components/postillustration";

export default function Preview() {
  return (
    <div>
      <Head>
        <title>Weebapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weeblogo40.png" />
      </Head>
      <Navbar/>
      <Illust/>
    </div>
  );
}
